# Generated by Django 4.2.7 on 2023-11-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_loghistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisableDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disable", models.TextField()),
            ],
        ),
    ]
