# Generated by Django 4.2.7 on 2023-12-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_disableday"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin_Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.TextField()),
            ],
        ),
    ]
