# Generated by Django 4.2.7 on 2023-12-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_admin_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agree_Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.TextField()),
            ],
        ),
    ]
